board: PiBotV49P
name: Axolex 3030
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: NO_PIN
  homing_runs: 2
  x:
    steps_per_mm: 1600.000
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 285.000
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: false
      seek_mm_per_min: 800.000
      feed_mm_per_min: 25.000
      settle_ms: 500
      #seek_scaler: 1.100
      #feed_scaler: 1.100
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.35:low
      pulloff_mm: 1.000
      hard_limits: true
      stepstick:
        disable_pin: I2SO.0
        step_pin: I2SO.2
        direction_pin: I2SO.1
        ms3_pin: I2SO.3:high        
  y:
    steps_per_mm: 1600.000
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 290.000
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: true
      seek_mm_per_min: 800.000
      feed_mm_per_min: 25.000
      settle_ms: 500
      #seek_scaler: 1.100
      #feed_scaler: 1.100
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.32:low
      pulloff_mm: 1.000
      hard_limits: true
      stepstick:
        disable_pin: I2SO.7
        step_pin: I2SO.5
        direction_pin: I2SO.4:low
        ms3_pin: I2SO.6:high
  z:
    steps_per_mm: 1600.000
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 68.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0
      seek_mm_per_min: 800.000
      feed_mm_per_min: 25.000
      settle_ms: 500
      #seek_scaler: 1.100
      #feed_scaler: 1.100
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.33:low
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        disable_pin: I2SO.8
        step_pin: I2SO.10
        direction_pin: I2SO.9
        ms3_pin: I2SO.11:high
  # a:
  #   steps_per_mm: 53.400
  #   max_rate_mm_per_min: 5000.000
  #   acceleration_mm_per_sec2: 100.000
  #   max_travel_mm: 960.000
  #   soft_limits: false
  #   homing:
  #     cycle: 2
  #     positive_direction: false
  #     mpos_mm: 150.000
  #     feed_mm_per_min: 100.000
  #     seek_mm_per_min: 200.000
  #     settle_ms: 500
  #     seek_scaler: 1.100
  #     feed_scaler: 1.100

  #   motor0:
  #     limit_neg_pin: gpio.36:low
  #     limit_pos_pin: NO_PIN
  #     limit_all_pin: NO_PIN
  #     hard_limits: false
  #     pulloff_mm: 3.000
  #     standard_stepper:
  #       step_pin: I2SO.13
  #       direction_pin: I2SO.12
  #       disable_pin: I2SO.15

  # b:
  #   steps_per_mm: 808.000
  #   max_rate_mm_per_min: 5000.000
  #   acceleration_mm_per_sec2: 100.000
  #   max_travel_mm: 200.000
  #   soft_limits: false
  #   homing:
  #     cycle: 1
  #     positive_direction: false
  #     mpos_mm: 150.000
  #     feed_mm_per_min: 100.000
  #     seek_mm_per_min: 800.000
  #     settle_ms: 500
  #     seek_scaler: 1.100
  #     feed_scaler: 1.100

  #   motor0:
  #     limit_neg_pin: NO_PIN
  #     limit_pos_pin: NO_PIN
  #     limit_all_pin: NO_PIN
  #     hard_limits: false
  #     pulloff_mm: 3.000
  #     standard_stepper:
  #       step_pin: I2SO.18
  #       direction_pin: I2SO.17
  #       disable_pin: I2SO.16

  # c:
  #   steps_per_mm: 808.000
  #   max_rate_mm_per_min: 5000.000
  #   acceleration_mm_per_sec2: 100.000
  #   max_travel_mm: 200.000
  #   soft_limits: false
  #   homing:
  #     cycle: 1
  #     positive_direction: false
  #     mpos_mm: 150.000
  #     feed_mm_per_min: 100.000
  #     seek_mm_per_min: 800.000
  #     settle_ms: 500
  #     seek_scaler: 1.100
  #     feed_scaler: 1.100

  #   motor0:
  #     limit_neg_pin: NO_PIN
  #     limit_pos_pin: NO_PIN
  #     limit_all_pin: NO_PIN
  #     hard_limits: false
  #     pulloff_mm: 3.000
  #     standard_stepper:
  #       step_pin: I2SO.21
  #       direction_pin: I2SO.20
  #       disable_pin: I2SO.23

########//gpio.2 and gpio.26 need :pu when use for input

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17


spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18


sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5

junction_deviation_mm: 0.010
verbose_errors: true
start:
  check_limits: true
  must_home: true

# # Begin OLED
# i2c0:
#    sda_pin: gpio.27
#    scl_pin: gpio.25

# oled:
#    i2c_num: 0
#    i2c_address: 60
#    width: 128
#    height: 64
#    radio_delay_ms: 1000

## FluidPendant
uart1:
  #Yellow 25, White 27
  txd_pin: gpio.27
  rxd_pin: gpio.25
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 1000000
  mode: 8N1
uart_channel1:
 report_interval_ms: 75
 uart_num: 1

# # Begin relay
# relay:
#   direction_pin: NO_PIN
#   output_pin: I2SO.20
#   enable_pin: NO_PIN
#   disable_with_s0: false
#   s0_with_disable: true
#   spinup_ms: 0
#   spindown_ms: 0
#   tool_num: 0
#   speed_map: 0=0.000% 0=100.000% 1=100.000%
#   off_on_alarm: false

# Begin H100 RS485
uart2:
  txd_pin: gpio.15
  rxd_pin: gpio.16
  rts_pin: gpio.14
  baud: 9600
  mode: 8N1

H100:
  uart_num: 2
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 0=25% 6000=25% 24000=100%
  off_on_alarm: true
  #debug: 3
  atc: atc_manual

coolant:
  flood_pin: I2SO.23
  mist_pin: I2SO.21
  delay_ms: 0

probe:
  pin: gpio.2:low:pu
  toolsetter_pin: gpio.26:high:pu
  #toolsetter_pin: NO_PIN
  check_mode_start: true
  hard_stop: false
  probe_hard_limit: true

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: gpio.39:low
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  #fault_pin: gpio.36:low
  fault_pin: NO_PIN
  estop_pin: gpio.34:low
  homing_button_pin: NO_PIN

atc_manual:
  safe_z_mpos_mm: -1.000000
  probe_seek_rate_mm_per_min: 160.000000
  probe_feed_rate_mm_per_min: 40.000000
  change_mpos_mm: 280.000 -4.200 -1.000000
  ets_mpos_mm: 220.003 -4.200 -40.000
  ets_rapid_z_mpos_mm: -1.000000


################################################################################################################################

# #begin Laser
# Laser:
  # pwm_hz: 5000
  # output_pin: gpio.4
  # enable_pin: gpio.12
  # disable_with_s0: false
  # s0_with_disable: true
  # tool_num: 1
  # speed_map: 0=0.000% 255=100.000%
  # off_on_alarm: true
# Laser:
#   pwm_hz: 5000
#   output_pin: gpio.12
#   enable_pin: NO_PIN
#   disable_with_s0: false
#   s0_with_disable: true
#   tool_num: 2
#   speed_map: 0=0.000% 255=100.000%
#   off_on_alarm: true


# Using MOSFETs (Check Spindle Pin Usage)
# coolant:
  # flood_pin: gpio.12
  # mist_pin: gpio.4
  # delay_ms: 0


  

